language: ruby
rvm:
  - 2.2
before_script:
  - gem install awesome_bot
script:
  - awesome_bot README.md --white-list 'posts.specterops.io,www.fireeye.com,www.alienvault.com,www.blackbagtech.com,arstechnica.com'